pipeline:
  # 1. build the new docker image from Dockerfile 
  # 2. push to Nexus with tag 0.1.1, so that this image will be used by kube-deploy-test.yml
  push_to_nexus:
    image: plugins/docker
    repo: nexus.teamdigitale.test/ml-api
    registry: nexus.teamdigitale.test:8081
    tags: "test"
    username: daf
    password: aquaiH3e
    dockerfile: outbox-classification/web-api/Dockerfile
    insecure: true

  # deploy the built image to Kubernetes
  # deploy_to_kube:
  #   image: vallard/drone-kube
  #   template: kube-deploy-test.yml
  #   namespace: default
  #   # server: ?